apt-get install git -y
apt-get install python-dev -y
apt-get install python-pip -y
apt-get install python-setuptools -y
apt-get install nginx -y
apt-get install redis-server -y
apt-get install supervisor -y
apt-get install memcahced -y
apt-get install mysql-server -y
